[package]
name = "whatnow"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.6.18"
axum-extra = { version = "0.8.0", features = ["cookie"] }
maud = { version = "0.25.0", features = ["axum"] }
shuttle-axum = "0.28.0"
shuttle-runtime = "0.28.0"
tokio = "1.28.2"
